### ISSUE TITLE
cant get line height values in pixels

### ISSUE THREAD

**Issue by oriziv** [jxnblk/figma-theme#4]
Hi

I'm using your code in order to get the theme from figma.
i have noticed that the output json styles for line height extract it in percentage which is not convertable to pixels 

can you adapt your code to extract the styles for line heights in pixels ? 
(opened PR)
Thanks
Ori

**Comment by jxnblk** [comment]
Generally you shouldn't use absolute units (e.g. pixels) for line height, but you could calculate what the value would be based on the font size

**Comment by oriziv** [comment]
Is it possible to have that option via configuration at least?
Thanks!

**Comment by jxnblk** [comment]
I don't plan on transforming the values returned from the API like that, but you can always fork this repo

**Comment by oriziv** [comment]
Ok thanks
